version: "3.7"

services:
  # Transfers
  transfers:
    image: mojaloop/poc-architecture:v0.19
#    container_name: transfers
    command: npm run start:transfers
#    ports:
#      - "3000:3001"
    environment:
      - LOG_LEVEL=info
      - REDIS_HOST=redis://192.168.1.95:6379
      - KAFKA_HOST=192.168.1.95:9092

  # Participants
  participants:
    image: mojaloop/poc-architecture:v0.19
#    container_name: participants
    command: npm run start:participants
#    ports:
#       - "3000:3002"
    environment:
      - LOG_LEVEL=info
      - REDIS_HOST=redis://192.168.1.95:6379
      - KAFKA_HOST=192.168.1.95:9092

#
#  kafka:
#    image: johnnypark/kafka-zookeeper:2.3.0
#    container_name: kafka
#    volumes:
#      - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#    environment:
#      - ZOO_LOG4J_PROP=WARN
#    networks:
#      - mojaloop-poc
#    healthcheck:
#      test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","172.17.0.1:9092"]
#      timeout: 20s
#      retries: 10
#      start_period: 40s
#      interval: 30s
#
#  redis:
#    container_name: redis
#    image: "redis:5.0.4-alpine"
#    ports:
#      - "6379:6379"
#    networks:
#      - mojaloop-poc
#    restart: always

#  simulator:
#    image: mojaloop/simulator:v9.5.0
#    container_name: simulator
#    ports:
#      - "8444:8444"
#    environment:
#      - LOG_LEVEL=info
#      - TRANSFERS_ENDPOINT=http://host.docker.internal:3000
#      - QUOTES_ENDPOINT=http://host.docker.internal:3002
#      - PARTIES_ENDPOINT=http://host.docker.internal:4002
#      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
#      - TRANSFERS_FULFILMENT=XoSz1cL0tljJSCp_VtIYmPNw-zFUgGfbUqf69AagUzY
#      - TRANSFERS_CONDITION=HOr22-H3AfTDHrSkPjJtVPRdKouuMkDXTR4ejlQa8Ks
#
#    healthcheck:
#      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8444/health"]
#      timeout: 20s
#      retries: 10
#      interval: 30s
