{
 "title": "Mojaloop - PoC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing time stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(moja_tx_transfer_bucket{le=\"1\"}[${__range_s}s]))",
     "legendFormat": "Less than 1 sec"
    },
    {
     "expr": "sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_tx_transfer_bucket{le=\"1\"}[${__range_s}s]))",
     "legendFormat": "More than 1 sec"
    },
    {
     "expr": "sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_tx_transfer_bucket{le=\"2\"}[${__range_s}s]))",
     "legendFormat": "More than 2 sec"
    },
    {
     "expr": "sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_tx_transfer_bucket{le=\"5\"}[${__range_s}s]))",
     "legendFormat": "More than 5 sec"
    }
   ]
  },
  { "title": "Mojaloop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Mojaloop - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_tx_transfer_count[30s])) by (success)",
     "legendFormat": "moja_tx_transfer - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_tx_transfer_prepare_count[30s])) by (success)",
     "legendFormat": "moja_tx_transfer_prepare - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_tx_transfer_fulfil_count[30s])) by (success)",
     "legendFormat": "moja_tx_transfer_fulfil - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_tx_transfer_count[30s]))",
     "legendFormat": "moja_tx_transfer - avg"
    },
    {
     "expr": "sum(rate(moja_tx_transfer_prepare_count[30s]))",
     "legendFormat": "moja_tx_transfer_prepare - avg"
    },
    {
     "expr": "sum(rate(moja_tx_transfer_fulfil_count[30s]))",
     "legendFormat": "moja_tx_transfer_fulfil - avg"
    },
    {
     "expr": "sum(rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[30s])) by (app, success)",
     "legendFormat": "Transfers API Prepare - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[30s])) by (app, success)",
     "legendFormat": "Transfers API Fulfill - success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[30s])) by (app, action, status, success)",
     "legendFormat": "Notification Delivery - {{action}} - {{status}} - success:{{success}}"
    },
    {
     "expr": "sum(rate(poc_tran_transferEvtHandler_count[30s])) by (success)",
     "legendFormat": "Transfer Evt - {{success}}"
    },
    {
     "expr": "sum(rate(poc_tran_transferCmdHandler_count[30s])) by (success)",
     "legendFormat": "Transfer Cmd - {{success}}"
    },
    {
     "expr": "sum(rate(poc_part_participantEvtHandler_count[30s])) by (success)",
     "legendFormat": "Participants Evt - {{success}}"
    },
    {
     "expr": "sum(rate(poc_part_participantCmdHandler_count[30s])) by (success)",
     "legendFormat": "Participants Cmd - {{success}}"
    },
    {
     "expr": "sum(rate(poc_part_participantEvtHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Participants Evt - {{success}} - {{evtname}}"
    },
    {
     "expr": "sum(rate(poc_part_participantCmdHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Participants Cmd - {{success}} - {{evtname}}"
    },
    {
     "expr": "sum(rate(poc_tran_transferEvtHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Transfer Evt - {{success}} -- {{evtname}}"
    },
    {
     "expr": "sum(rate(poc_tran_transferCmdHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Transfer Cmd - {{success}} -- {{evtname}}"
    }
   ]
  },
  {
   "title": "Mojaloop - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(moja_transfer_prepare_sum{serviceName=\"ml-service\"}[30s]) / rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[30s]))",
     "legendFormat": "Transfer API Prepare - Average"
    },
    {
     "expr": "avg(rate(moja_transfer_fulfil_sum{serviceName=\"ml-service\"}[30s]) / rate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[30s]))",
     "legendFormat": "Transfer API Fulfil - Average"
    },
    {
     "expr": "avg(rate(moja_notification_event_delivery_sum{serviceName=\"ml-handler-notification\"}[30s]) / rate(moja_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[30s])) by (action, status, success)",
     "legendFormat": "Notification Deliveries - {{action}} - {{status}} - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_tx_transfer_prepare_sum[30s]) / rate(moja_tx_transfer_prepare_count[30s])) by (success)",
     "legendFormat": "moja_tx_transfer_prepare - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_tx_transfer_fulfil_sum[30s]) / rate(moja_tx_transfer_fulfil_count[30s])) by (success)",
     "legendFormat": "moja_tx_transfer_fulfil - success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_tx_transfer_sum[30s]) / irate(moja_tx_transfer_count[30s]))",
     "legendFormat": "moja_tx_transfer - avg"
    },
    {
     "expr": "avg(rate(moja_tx_transfer_prepare_sum[30s]) / rate(moja_tx_transfer_prepare_count[30s]))",
     "legendFormat": "moja_tx_transfer_prepare - avg"
    },
    {
     "expr": "avg(rate(moja_tx_transfer_fulfil_sum[30s]) / rate(moja_tx_transfer_fulfil_count[30s]))",
     "legendFormat": "moja_tx_transfer_fulfil - avg"
    },
    {
     "expr": "avg(rate(poc_part_participantCmdHandler_sum[30s]) / rate(poc_part_participantCmdHandler_count[30s]))",
     "legendFormat": "Participant Cmd - avg"
    },
    {
     "expr": "avg(rate(poc_part_participantEvtHandler_sum[30s]) / rate(poc_part_participantEvtHandler_count[30s]))",
     "legendFormat": "Participant Evt - avg"
    },
    {
     "expr": "avg(rate(poc_tran_transferCmdHandler_sum[30s]) / rate(poc_tran_transferCmdHandler_count[30s]))",
     "legendFormat": "Transfer Cmd - avg"
    },
    {
     "expr": "avg(rate(poc_tran_transferEvtHandler_sum[30s]) / rate(poc_tran_transferEvtHandler_count[30s]))",
     "legendFormat": "Transfer Evt - avg"
    },
    {
     "expr": "avg(rate(poc_tran_transferEvtHandler_sum[30s]) / rate(poc_tran_transferEvtHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Transfer Evt - avg - {{success}} - {{evtname}}"
    },
    {
     "expr": "avg(rate(poc_tran_transferCmdHandler_sum[30s]) / rate(poc_tran_transferCmdHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Transfer Cmd - avg - {{success}} - {{evtname}}"
    },
    {
     "expr": "avg(rate(poc_part_participantEvtHandler_sum[30s]) / rate(poc_part_participantEvtHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Participant Evt - avg - {{success}} - {{evtname}}"
    },
    {
     "expr": "avg(rate(poc_part_participantCmdHandler_sum[30s]) / rate(poc_part_participantCmdHandler_count[30s])) by (success, evtname)",
     "legendFormat": "Participant Cmd - avg - {{success}} - {{evtname}}"
    }
   ]
  },
  { "title": "Current OP/s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Financial Transfers / Sec",
   "type": "singlestat",
   "description": "Financial Transfers / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_tx_transfer_count[30s]))",
     "legendFormat": "Financial Transfers / sec"
    }
   ]
  },
  {
   "title": "Financial Prepares / sec",
   "type": "singlestat",
   "description": "Financial Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_tx_transfer_prepare_count[30s]))",
     "legendFormat": "Transfers / Sec"
    }
   ]
  },
  {
   "title": "Financial Fulils / sec",
   "type": "singlestat",
   "description": "Financial Fulils / sec",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_tx_transfer_fulfil_count[30s]))",
     "legendFormat": "Financial Fulfils / sec"
    }
   ]
  },
  {
   "title": "Transfers API Prepares / sec",
   "type": "singlestat",
   "description": "Transfers API Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[120s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfers API Fullfills / sec",
   "type": "singlestat",
   "description": "Transfers API Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[120s]))"
    }
   ]
  },
  {
   "title": "Notification Events / Sec",
   "type": "singlestat",
   "description": "Notification Events / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 26 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[120s]))",
     "legendFormat": "Notification Events / sec"
    }
   ]
  },
  {
   "title": "Financial Transfers 95th Quantile",
   "type": "singlestat",
   "description": "Financial Transfers 95th Quantile",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(moja_tx_transfer_bucket[${__range_s}s])) by (le))"
    }
   ]
  },
  {
   "title": "% > 1 Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s])) - sum(increase(moja_tx_transfer_bucket{le=\"1\"}[${__range_s}s]))) / sum(increase(moja_tx_transfer_bucket{le=\"+Inf\"}[${__range_s}s]))"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "ML API Lag by  Consumer Group",
   "type": "graph",
   "description": "ML API Lag by  Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "ML-API - Processed per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(moja_tx_transfer_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_tx_transfer_prepare_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer_prepare - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_tx_transfer_fulfil_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer_fulfil - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[30s])) by (app, success)",
       "legendFormat": "Transfers API Prepare - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[30s])) by (app, success)",
       "legendFormat": "Transfers API Fulfill - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[30s])) by (app, success)",
       "legendFormat": "Notification Events - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_notification_event_process_msg_count{serviceName=\"ml-handler-notification\"}[30s])) by (app, action, success)",
       "legendFormat": "Notification Events - {{action}} - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[30s])) by (app, action, status, success)",
       "legendFormat": "Notification Delivery - {{action}} - {{status}} - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[30s])) by (kubernetes_pod_name, success)",
       "legendFormat": "{{kubernetes_pod_name}} - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_notification_event_getEndpoint_count{serviceName=\"ml-handler-notification\"}[30s])) by (success)",
       "legendFormat": "Notification GetEndpoint - success:{{success}}"
      },
      {
       "expr": "sum(rate(moja_tx_transfer_count[30s]))",
       "legendFormat": "moja_tx_transfer - avg"
      },
      {
       "expr": "sum(rate(moja_tx_transfer_prepare_count[30s]))",
       "legendFormat": "moja_tx_transfer_prepare - avg"
      },
      {
       "expr": "sum(rate(moja_tx_transfer_fulfil_count[30s]))",
       "legendFormat": "moja_tx_transfer_fulfil - avg"
      }
     ]
    },
    {
     "title": "ML-API - Processing Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(moja_transfer_prepare_sum{serviceName=\"ml-service\"}[30s]) / rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[30s]))",
       "legendFormat": "Transfer API Prepare - Average"
      },
      {
       "expr": "avg(rate(moja_transfer_fulfil_sum{serviceName=\"ml-service\"}[30s]) / rate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[30s]))",
       "legendFormat": "Transfer API Fulfil - Average"
      },
      {
       "expr": "avg(rate(moja_notification_event_sum{serviceName=\"ml-handler-notification\"}[30s]) / rate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[30s]))",
       "legendFormat": "Notification Events - Average"
      },
      {
       "expr": "avg(rate(moja_notification_event_delivery_sum{serviceName=\"ml-handler-notification\"}[30s]) / rate(moja_notification_event_delivery_count{serviceName=\"ml-handler-notification\"}[30s])) by (action, status, success)",
       "legendFormat": "Notification Deliveries - {{action}} - {{status}} - success:{{success}}"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_sum[30s]) / rate(moja_tx_transfer_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer - success:{{success}}"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_prepare_sum[30s]) / rate(moja_tx_transfer_prepare_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer_prepare - success:{{success}}"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_fulfil_sum[30s]) / rate(moja_tx_transfer_fulfil_count[30s])) by (success)",
       "legendFormat": "moja_tx_transfer_fulfil - success:{{success}}"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_sum[30s]) / irate(moja_tx_transfer_count[30s]))",
       "legendFormat": "moja_tx_transfer - avg"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_prepare_sum[30s]) / rate(moja_tx_transfer_prepare_count[30s]))",
       "legendFormat": "moja_tx_transfer_prepare - avg"
      },
      {
       "expr": "avg(rate(moja_tx_transfer_fulfil_sum[30s]) / rate(moja_tx_transfer_fulfil_count[30s]))",
       "legendFormat": "moja_tx_transfer_fulfil - avg"
      }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "ML-API- Notification Handler Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_notification_event_count{serviceName=\"ml-handler-notification\", success!='true'}[30s])) by (app, success, error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Total Errors for range",
   "type": "graph",
   "description": "Total Errors for range ",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(moja_notification_event_bucket{le=\"+Inf\", serviceName=\"ml-handler-notification\", success!='true'}[${__range_s}s])) by (app, success, error)",
     "legendFormat": "notification-handler-{{error}}"
    },
    {
     "expr": "sum(increase(moja_notification_event_bucket{le=\"+Inf\", serviceName=\"ml-service\", success!='true'}[${__range_s}s])) by (app, success, error)",
     "legendFormat": "ml-service-{{error}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mojaloop API Adapter Total CPU Usage",
     "type": "singlestat",
     "description": "Mojaloop API Adapter Total CPU Usage",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 41 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api.*'}[2m]))"
      }
     ]
    },
    {
     "title": "ML API Service CPU Usage",
     "type": "singlestat",
     "description": "ML API Service CPU Usage",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 41 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-service.*'}[2m]))"
      }
     ]
    },
    {
     "title": "ML API Notification CPU Usage",
     "type": "singlestat",
     "description": "ML API Notification CPU Usage",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 41 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-handler-notification.*'}[2m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "ML API - Memoy Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "moja_nodejs_heap_size_total_bytes{serviceName=~\"ml-s.*\"}",
       "legendFormat": "heap_total-{{kubernetes_pod_name}}"
      },
      {
       "expr": "moja_nodejs_heap_size_used_bytes{serviceName=~\"ml-s.*\"}",
       "legendFormat": "heap_used-{{kubernetes_pod_name}}"
      },
      {
       "expr": "moja_nodejs_external_memory_bytes{serviceName=~\"ml-s.*\"}",
       "legendFormat": "ext_memory-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "ML-API  -  CPU Usage in Seconds by Pod",
     "type": "graph",
     "description": "ML-API  -  CPU Usage in Seconds by Pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(moja_process_cpu_seconds_total{serviceName=~\"ml-.*\"}[30s]) * 100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "ML-API - # Nodes for each Components",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*ml-api-.*\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*simnotifhandler.*\"}",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\".*ml-api-.*\"}",
     "legendFormat": "available-{{deployment}}"
    },
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\".*simnotifhandler.*\"}",
     "legendFormat": "available-{{deployment}}"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=~\".*ml-api-.*\",}",
     "legendFormat": "status-{{deployment}}"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*poc-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ML-API  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=~\"ml.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}